;==============================================================================
;
; Sia x86 Library by fearless
;
; http://github.com/mrfearless
;
;==============================================================================

.CODE

;------------------------------------------------------------------------------
; WalletAddressGet requests a new address from the /wallet/address endpoint
;------------------------------------------------------------------------------
Sia_WalletAddressGet PROC hSia:DWORD, lpWalletAddressGet:DWORD
    Invoke sia_api_wallet_address, hSia, lpWalletAddressGet
    ret
Sia_WalletAddressGet ENDP

;------------------------------------------------------------------------------
; WalletAddressesGet requests the wallets known addresses from the /wallet/addresses endpoint
;------------------------------------------------------------------------------
Sia_WalletAddressesGet PROC hSia:DWORD, lpWalletAddressesGet:DWORD
    Invoke sia_api_wallet_addresses, hSia, lpWalletAddressesGet
    ret
Sia_WalletAddressesGet ENDP

;------------------------------------------------------------------------------
; WalletChangePasswordPost uses the /wallet/changepassword endpoint to change the wallet's password.
;------------------------------------------------------------------------------
Sia_WalletChangePasswordPost PROC hSia:DWORD, lpszCurrentPassword:DWORD, lpszNewPassword:DWORD
    .IF lpszCurrentPassword == NULL || lpszNewPassword == NULL
        xor eax, eax
        ret
    .ENDIF
    Invoke RpcSetQueryParameters, hSia, CTEXT("encryptionpassword"), lpszCurrentPassword, 0
    Invoke RpcSetQueryParameters, hSia, CTEXT("newpassword"), lpszNewPassword, 0
    Invoke sia_api_wallet_changepassword, hSia
    ret
Sia_WalletChangePasswordPost ENDP

;------------------------------------------------------------------------------
; WalletInitPost uses the /wallet/init endpoint to initialize and encrypt a wallet
;------------------------------------------------------------------------------
Sia_WalletInitPost PROC hSia:DWORD, lpszPassword:DWORD, bForce:DWORD, lpWalletInitPost:DWORD
    Invoke RpcSetQueryParameters, hSia, CTEXT("encryptionpassword"), lpszPassword, 0
    .IF bForce == TRUE
        Invoke RpcSetQueryParameters, hSia, CTEXT("force"), CTEXT("true"), 0
    .ELSE
        Invoke RpcSetQueryParameters, hSia, CTEXT("force"), CTEXT("false"), 0
    .ENDIF
    Invoke sia_api_wallet_init, hSia, lpWalletInitPost
    ret
Sia_WalletInitPost ENDP

;------------------------------------------------------------------------------
; WalletInitSeedPost uses the /wallet/init/seed endpoint to initialize and encrypt a wallet using a given seed.
;------------------------------------------------------------------------------
Sia_WalletInitSeedPost PROC hSia:DWORD, lpszPassword:DWORD, bForce:DWORD
    Invoke RpcSetQueryParameters, hSia, CTEXT("encryptionpassword"), lpszPassword, 0
    .IF bForce == TRUE
        Invoke RpcSetQueryParameters, hSia, CTEXT("force"), CTEXT("true"), 0
    .ELSE
        Invoke RpcSetQueryParameters, hSia, CTEXT("force"), CTEXT("false"), 0
    .ENDIF
    Invoke sia_api_wallet_init_seed, hSia
    ret
Sia_WalletInitSeedPost ENDP

;------------------------------------------------------------------------------
; WalletGet requests the /wallet api resource
;------------------------------------------------------------------------------
Sia_WalletGet PROC hSia:DWORD, lpWalletGet:DWORD
    Invoke sia_api_wallet, hSia, lpWalletGet
    ret
Sia_WalletGet ENDP

;------------------------------------------------------------------------------
; WalletLastAddressesGet returns the count last addresses generated by the wallet
; in reverse order. That means the last generated address will be the first one in the slice.
;------------------------------------------------------------------------------
Sia_WalletLastAddressesGet PROC hSia:DWORD, dwCount:DWORD, lpWalletAddressesGet:DWORD
    Invoke RpcSetQueryParameters, hSia, CTEXT("count"), 0, dwCount
    Invoke sia_api_wallet_seedaddrs, hSia, lpWalletAddressesGet
    ret
Sia_WalletLastAddressesGet ENDP

;------------------------------------------------------------------------------
; WalletLockPost uses the /wallet/lock endpoint to lock the wallet
;------------------------------------------------------------------------------
Sia_WalletLockPost PROC hSia:DWORD
    Invoke sia_api_wallet_lock, hSia
    ret
Sia_WalletLockPost ENDP

;------------------------------------------------------------------------------
; WalletSeedPost uses the /wallet/seed endpoint to add a seed to the wallet's list of seeds.
;------------------------------------------------------------------------------
Sia_WalletSeedPost PROC hSia:DWORD, lpszSeed:DWORD, lpszPassword:DWORD
    Invoke RpcSetQueryParameters, hSia, CTEXT("encryptionpassword"), lpszPassword, 0
    Invoke RpcSetQueryParameters, hSia, CTEXT("seed"), lpszSeed, 0
    Invoke sia_api_wallet, hSia, NULL
    ret
Sia_WalletSeedPost ENDP

;------------------------------------------------------------------------------
; WalletSeedsGet uses the /wallet/seeds endpoint to return the wallet's current seeds
;------------------------------------------------------------------------------
Sia_WalletSeedsGet PROC hSia:DWORD, lpWalletSeedsGet:DWORD
    Invoke sia_api_wallet_seeds, hSia, lpWalletSeedsGet
    ret
Sia_WalletSeedsGet ENDP

;------------------------------------------------------------------------------
; WalletSiacoinsMultiPost uses the /wallet/siacoin api endpoint to send money to multiple addresses at once
;------------------------------------------------------------------------------
Sia_WalletSiacoinsMultiPost PROC hSia:DWORD, lpArrayOutputs:DWORD, lpWalletSiacoinsPost:DWORD
    ret
Sia_WalletSiacoinsMultiPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletSiacoinsPost PROC hSia:DWORD
    ret
Sia_WalletSiacoinsPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletSignPost PROC hSia:DWORD
    ret
Sia_WalletSignPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletSiafundsPost PROC hSia:DWORD
    ret
Sia_WalletSiafundsPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletSiagKeyPost PROC hSia:DWORD
    ret
Sia_WalletSiagKeyPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletSweepPost PROC hSia:DWORD
    ret
Sia_WalletSweepPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletTransactionsGet PROC hSia:DWORD
    ret
Sia_WalletTransactionsGet ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletTransactionGet PROC hSia:DWORD
    ret
Sia_WalletTransactionGet ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletUnlockPost PROC hSia:DWORD
    ret
Sia_WalletUnlockPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletUnlockConditionsGet PROC hSia:DWORD
    ret
Sia_WalletUnlockConditionsGet ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletUnspentGet PROC hSia:DWORD
    ret
Sia_WalletUnspentGet ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletWatchGet PROC hSia:DWORD
    ret
Sia_WalletWatchGet ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletWatchAddPost PROC hSia:DWORD
    ret
Sia_WalletWatchAddPost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_WalletWatchRemovePost PROC hSia:DWORD
    ret
Sia_WalletWatchRemovePost ENDP

;------------------------------------------------------------------------------
; 
;------------------------------------------------------------------------------
Sia_Wallet033xPost PROC hSia:DWORD
    ret
Sia_Wallet033xPost ENDP




